// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qyGGbyHXmFYBhlyqHWcwC2D5ku0CZY0',
    appId: '1:373016114878:web:93996bd8e6bd226df110ef',
    messagingSenderId: '373016114878',
    projectId: 'noteapp-1b52d',
    authDomain: 'noteapp-1b52d.firebaseapp.com',
    storageBucket: 'noteapp-1b52d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8skizEmIaWcz0IE_LqydW5jVCLC_mYBQ',
    appId: '1:373016114878:android:ffcabcab9464fb17f110ef',
    messagingSenderId: '373016114878',
    projectId: 'noteapp-1b52d',
    storageBucket: 'noteapp-1b52d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoj3HRb2niGapGxzCOoId648IpCeAEgrA',
    appId: '1:373016114878:ios:5a5f781bdd5a9b18f110ef',
    messagingSenderId: '373016114878',
    projectId: 'noteapp-1b52d',
    storageBucket: 'noteapp-1b52d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoj3HRb2niGapGxzCOoId648IpCeAEgrA',
    appId: '1:373016114878:ios:5a5f781bdd5a9b18f110ef',
    messagingSenderId: '373016114878',
    projectId: 'noteapp-1b52d',
    storageBucket: 'noteapp-1b52d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9qyGGbyHXmFYBhlyqHWcwC2D5ku0CZY0',
    appId: '1:373016114878:web:8154d6e7b9828dc5f110ef',
    messagingSenderId: '373016114878',
    projectId: 'noteapp-1b52d',
    authDomain: 'noteapp-1b52d.firebaseapp.com',
    storageBucket: 'noteapp-1b52d.firebasestorage.app',
  );
}
